// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className="h-screen">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Voice AI Agent",
//   description: "Colorful ambient chat UI with audio + SSE",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className="h-screen">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground h-screen`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";

/* =========================
   Fonts
   ========================= */
const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const fira = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

/* =========================
   Metadata
   ========================= */
export const metadata: Metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Voice AI Agent",
  description:
    "A stunning ambient chat interface with real-time voice and AI conversation streaming.",
  keywords: [
    "AI",
    "Voice Assistant",
    "Chatbot",
    "Next.js",
    "Tailwind",
    "Ambient UI",
    "SSE",
  ],
  authors: [{ name: "Voice Agent" }],
  openGraph: {
    title: "Voice AI Agent",
    description:
      "Talk and type in a beautiful, immersive chat interface powered by AI and voice streaming.",
    type: "website",
    url: "http://localhost:3000",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Voice AI Agent Preview",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Voice AI Agent",
    description:
      "Chat with your AI in real time — voice, text, and beautiful ambiance.",
    images: ["/og-image.png"],
  },
};

/* =========================
   Root Layout
   ========================= */
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <body
        className={`${inter.variable} ${fira.variable} antialiased min-h-screen bg-gradient-to-br from-slate-950 via-purple-950 to-indigo-950 text-white relative overflow-hidden`}
      >
        {/* 🌌 Animated Ambient Glow */}
        <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_80%_20%,rgba(147,51,234,0.25),transparent_60%),radial-gradient(circle_at_20%_80%,rgba(236,72,153,0.25),transparent_60%)] animate-pulse blur-3xl" />

        {/* 🌫️ Floating gradient particles */}
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute w-[400px] h-[400px] bg-pink-500/10 rounded-full blur-3xl top-20 left-20 animate-float-slow" />
          <div className="absolute w-[500px] h-[500px] bg-indigo-500/10 rounded-full blur-3xl bottom-20 right-20 animate-float-slower" />
        </div>

        {/* 🌈 Main Content */}
        <main className="relative z-10 flex flex-col min-h-screen">
          {children}
        </main>

        {/* 💫 Footer Glow Accent */}
        <div className="pointer-events-none fixed bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-pink-600/20 via-transparent to-transparent blur-3xl" />
      </body>
    </html>
  );
}
